config/routes.rb
Rails.application.routes.draw do
  root 'intro#index'
  get 'new_game' => 'intro#new_game'
  get 'valera' => 'valera#index'
  patch 'valera', controller: 'valera', action: :index
  get 'action' => 'valera_action#new'
  post 'action', controller: 'valera_action', action: :create
end

app/models/action_history.rb
class ActionHistory < ApplicationRecord
  belongs_to :valera, optional: true
  belongs_to :valera_action, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/max_characteristic.rb
class MaxCharacteristic < ApplicationRecord
  belongs_to :valera, optional: true
end

app/models/metro_characteristic.rb
class MetroCharacteristic < ApplicationRecord
  belongs_to :valera, optional: true
end

app/models/min_characteristic.rb
class MinCharacteristic < ApplicationRecord
  belongs_to :valera, optional: true
end

app/models/sleep_characteristic.rb
class SleepCharacteristic < ApplicationRecord
  belongs_to :valera, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one :valera, dependent: :destroy
end

app/models/valera.rb
class Valera < ApplicationRecord
  belongs_to :user, optional: true

  has_one :action_history, dependent: :destroy

  has_one :min_characteristic, dependent: :destroy
  has_one :max_characteristic, dependent: :destroy

  has_one :metro_characteristic, dependent: :destroy
  has_one :sleep_characteristic, dependent: :destroy
  has_one :work_characteristic, dependent: :destroy

  def with_id(id)
    create_characteristics
    fill_base_valera id
    fill_valera
    set_id_range_characteristic
    set_id_base_characteristic
    save_characteristics
    self
  end

  def create_characteristics
    self.max_characteristic = MaxCharacteristic.new
    self.min_characteristic = MinCharacteristic.new
    self.sleep_characteristic = SleepCharacteristic.new
    self.metro_characteristic = MetroCharacteristic.new
    self.work_characteristic = WorkCharacteristic.new
  end

  def set_id_range_characteristic
    max_characteristic.valera_id = id
    min_characteristic.valera_id = id
  end

  def set_id_base_characteristic
    sleep_characteristic.valera_id = id
    metro_characteristic.valera_id = id
    work_characteristic.valera_id = id
  end

  def save_characteristics
    max_characteristic.save!
    min_characteristic.save!
    sleep_characteristic.save!
    metro_characteristic.save!
    work_characteristic.save!
  end

  def load_range_characteristics
    self.max_characteristic = MaxCharacteristic.where(valera_id: id).first
    self.min_characteristic = MinCharacteristic.where(valera_id: id).first
  end

  def load_base_characteristics
    self.sleep_characteristic = SleepCharacteristic.where(valera_id: id).first
    self.metro_characteristic = MetroCharacteristic.where(valera_id: id).first
    self.work_characteristic = WorkCharacteristic.where(valera_id: id).first
  end

  def fill_base_valera(id)
    self.user_id = id
    self.health = max_characteristic.health
    self.mana = max_characteristic.mana
  end

  def fill_valera
    self.cheerfulness = max_characteristic.cheerfulness
    self.fatigue = max_characteristic.fatigue
    self.money = max_characteristic.money
  end

  def dead?
    health <= min_characteristic.health ||
      cheerfulness <= min_characteristic.cheerfulness || money <= min_characteristic.money
  end

  def action(action)
    return if can_not_valera_work?(action.name)

    condition_action(action)
    get_valera_tips?(action)
    self.money += action.money
    self.mana += action.mana
    self.fatigue += action.fatigue
    check_base_characteristics
    check_characteristics
    self
  end

  def condition_action(action)
    self.health += action.health unless heal_valera_in_sleep?(action.name)
    self.cheerfulness += action.cheerfulness unless cheerfulness_valera_in_sleep?(action.name)
  end

  def can_not_valera_work?(action_name)
    action_name == 'work' and self.mana >= work_characteristic.mana and self.fatigue >= work_characteristic.fatigue
  end

  def cheerfulness_valera_in_sleep?(action_name)
    action_name == 'sleep' and self.mana < sleep_characteristic.cheerfulness_mana
  end

  def heal_valera_in_sleep?(action_name)
    action_name == 'sleep' and self.mana > sleep_characteristic.heal_mana
  end

  def get_valera_tips?(action)
    if action.name == 'metro' && self.mana >= metro_characteristic.min_mana &&
       self.mana <= metro_characteristic.max_mana
      self.money += metro_characteristic.tips
    end
  end

  def check_base_characteristics
    self.health = [[self.health, max_characteristic.health].min, min_characteristic.health].max
    self.mana = [[self.mana, max_characteristic.mana].min, min_characteristic.mana].max
  end

  def check_characteristics
    self.cheerfulness = [[self.cheerfulness, max_characteristic.cheerfulness].min, min_characteristic.cheerfulness].max
    self.fatigue = [[self.fatigue, max_characteristic.fatigue].min, min_characteristic.fatigue].max
  end
end

app/models/valera_action.rb
class ValeraAction < ApplicationRecord
  has_one :action_history, dependent: :destroy
end

app/models/work_characteristic.rb
class WorkCharacteristic < ApplicationRecord
  belongs_to :valera, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  # rescue_from ActiveRecord::RecordNotFound, :with => :rescue_404
  # rescue_from ActionController::RoutingError, :with => :rescue_404

  # def rescue_404
  #   redirect_to '/'
  # end
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  def index
    redirect_to '/valera' if signed_in?
  end

  def new_game; end
end

app/controllers/valera_action_controller.rb
class ValeraActionController < ApplicationController
  def new
    @valera_action_form = ValeraActionForm.new
  end

  def create
    @valera_action_form = ValeraActionForm.new(valera_action_form_params)
    if @valera_action_form.save
      redirect_to action_url, notice: "#{@valera_action_form.name} has been created"
    else
      render :new
    end
  end

  private

  def valera_action_form_params
    params.require(:valera_action_form).permit(:name, :description, :health, :mana, :cheerfulness, :fatigue, :money)
  end
end

app/controllers/valera_controller.rb
class ValeraController < ApplicationController
  def index
    redirect_to '/' and return unless defined? current_user.id

    set_valera
    set_actions

    @image = image_name

    return unless defined? action_params['action_id']

    action = find_action
    @valera.action(action)

    if @valera.dead?
      delete_valera
      redirect_to '/new_game' and return
    end

    write_action_to_history(action)
    update_characteristics
  end

  private

  def image_name
    return '1.jpg' if @valera.health >= @valera.max_characteristic.health * 0.7
    return '2.jpg' if @valera.health >= @valera.max_characteristic.health * 0.4

    '3.jpg'
  end

  def set_valera
    @valera = Valera.where(user_id: current_user.id).first
    if @valera
      @valera.load_range_characteristics
      @valera.load_base_characteristics
    else
      @valera = Valera.new.with_id(current_user.id)
      @valera.save!
    end
  end

  def set_actions
    @actions = ValeraAction.all
  end

  def find_action
    ValeraAction.where(id: action_params['action_id'].to_i).first
  end

  def update_characteristics
    respond_to do |format|
      format.js if @valera.save
    end
  end

  def delete_valera
    ActionHistory.destroy_by(valera_id: @valera.id)
    Valera.destroy_by(id: @valera.id)
  end

  def write_action_to_history(action)
    @history = ActionHistory.new
    @history.valera_id = @valera.id
    @history.valera_action_id = action.id
    @history.save!
  end

  def action_params
    params.require(:valera).permit(:action_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/valera_helper.rb
module ValeraHelper
end

app/views/intro/index.erb
<h1>Welcome to Valera's world</h1>

  <div class="row justify-content-center">
    <div class="col-2">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Sign in', sign_in_path, id: 'sign-in'%></li>
        <li><%= link_to 'Sign up', sign_up_path, class: ''%></li>
      </ul>
    </div>
  </div>

app/views/intro/new_game.erb
<h1>Valera exterminated!</h1>

<h2><%= link_to 'Start new game', valera_path, id: "new-game"%></h2>

<div id="img-block" class="row justify-content-center">
	<%= image_tag("dead.jpg", id: "valera", class: "col img") %>
</div>

app/views/layouts/_flashes.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <% alert_class = case key
                     when 'notice' then "success"
                     when 'alert' then "danger"
                     else key
                     end %>
    <%= content_tag :div, class: "alert alert-#{alert_class} alert-dismissible fade show" do %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= value %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid" id="menu">
    <%= link_to 'Valera-Online', root_path, class: 'navbar-brand' %>
    <% if signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to current_user.email, root_path, class: 'nav_link', id: 'email'%></li>
        </ul>
    <% end %>
 
    <ul class="nav navbar-nav pull-right">
      <% if signed_in? %>
      <li><%= link_to 'Sign out', sign_out_path, class: 'nav_link', id: 'sign-out', method: :delete %></li>
      <% else %>
      <li><%= link_to 'Sign in', sign_in_path, class: 'nav_link'%></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valera-Online</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/menu" %>
     
    <%= render "layouts/flashes" %>

    <div id="yield-block" class="container d-flex flex-column justify-content-center">
      <%= yield %>
    </div>

    <%= javascript_include_tag( 'application.js' ) %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form.label :email %>
<div class="text-field">
  <%= form.text_field :email, type: 'email', class: 'form-control'%>
</div>

<%= form.label :password %>
<div class="password-field">
  <%= form.password_field :password, class: 'form-control'%>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center">
  <div id="clearance" class="sign-up col-3">
    <h2><%= t(".title") %></h2>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit :class => 'form-control' %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path, class: 'link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/valera/_action.erb
<% for action in @actions do %>
  <div class="action_btn p-2">
    <%= form_with(model: @valera, local: false, id:"my-form") do |form| %>
      <%= form.hidden_field :action_id, value:action.id %>
      <%= form.submit action.description, class:"do_btn btn btn-primary", id:action.name%>
    <% end %>

    <button id="hide-btn<%= action.id %>" class="down hide_btn btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#action<%= action.id %>" aria-expanded="false" aria-controls="action<%= action.id %>"><span class="arr">&dArr;</span></button>

    <ul class="hide_list collapse multi-collapse" id="action<%= action.id %>">
      <% unless action.health == 0 %>
        <li><%= action.health %> health</li>
      <% end %>

      <% unless action.mana == 0 %>
        <li><%= action.mana %>  mana</li>
      <% end %>

      <% unless action.cheerfulness == 0 %>
        <li><%= action.cheerfulness %> cheerfulness</li>
      <% end %>

      <% unless action.fatigue == 0 %>
        <li><%= action.fatigue %> fatigue</li>
      <% end %>

      <% unless action.money == 0 %>
        <li><%= action.money %> $</li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/valera/_characteristics.erb
<div class="row stat-block">
  <div class="stat col-2">
    <p>Health:</p>
  </div>
  <div class="col-1"></div>
  <div class="col-8 pr-block">
    <div class="progress">
      <div id="health" class="progress-bar bg-danger" role="progressbar" style="width: <%=@valera.health%>%; color: black;" aria-valuemin="0" aria-valuemax="100"><%=@valera.health%>%</div>
    </div>
  </div>
</div>

<div class="row stat-block">
  <div class="stat col-2">
    <p>Mana:</p>
  </div>
  <div class="col-1"></div>
  <div class="col-8 pr-block">
    <div class="progress">
      <div id='mana' class="progress-bar" role="progressbar" style="width: <%=@valera.mana%>%; color: black;" aria-valuemin="0" aria-valuemax="100"><%=@valera.mana%>%</div>
    </div>
  </div>
</div>

<div class="row stat-block">
  <div class="stat col-2">
    <p>Cheerfulness:</p>
  </div>
  <div class="col-1"></div>

  <div class="col-8 pr-block">
    <div class="progress">
      <div id="cheerfulness" class="progress-bar bg-warning" role="progressbar" style="width: <%=(@valera.cheerfulness+@valera.max_characteristic.cheerfulness)*5 %>%; color: black;" aria-valuemin="0" aria-valuemax="100"><%=(@valera.cheerfulness+@valera.max_characteristic.cheerfulness)*5%>%</div>
    </div>
  </div>
</div>

<div class="row stat-block">
  <div class="stat col-2">
    <p>Fatigue:</p>
  </div>
  <div class="col-1"></div>
  <div class="col-8 pr-block">
    <div class="progress">
      <div id='fatigue' class="progress-bar bg-info" role="progressbar" style="width: <%=@valera.fatigue%>%; color: black;" aria-valuemin="0" aria-valuemax="100"><%=@valera.fatigue%>%</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <p id='money'>Money: <%=@valera.money%>$</p>
  </div>
</div>

app/views/valera/index.erb
<h2>Valera</h2>

<div id="img-block" class="row justify-content-center">
  <%= image_tag(@image, id: "valera", class:"col img") %>
</div>

<div class="container">
  <div class="row justify-content-center" id="characteristics">
    <%= render "characteristics" %>
  </div>

  <div class="d-flex flex-wrap justify-content-center">
    <%= render "valera/action" %>
  </div>

  <p id="temp_hidden"></p>
</div>

app/views/valera/index.js.erb
//= require jquery
//= require jquery_ujs


/* Characteristics */
$("#health").css("width", <%=@valera.health%> + "%");
$("#health").text(<%=@valera.health%> + "%");

$("#mana").css("width", <%=@valera.mana%> + "%");
$("#mana").text(<%=@valera.mana%> + "%");

$("#cheerfulness").css("width", <%=(@valera.cheerfulness+@valera.max_characteristic.cheerfulness)*5%> + "%");
$("#cheerfulness").text(<%=(@valera.cheerfulness+@valera.max_characteristic.cheerfulness)*5%> + "%");

$("#fatigue").css("width", <%=@valera.fatigue%> + "%");
$("#fatigue").text(<%=@valera.fatigue%> + "%");

$("#money").replaceWith("<p id='money'>Money: <%=@valera.money%>$</p>");

/* Images */
$('#temp_hidden').html(<%=@valera.max_characteristic.health%>);
var max_health = parseInt($("#temp_hidden").text());

$('#temp_hidden').html(<%=@valera.max_characteristic.cheerfulness*10%>);
var max_cheerfulness = parseInt($("#temp_hidden").text());

$('#temp_hidden').html(<%=@valera.min_characteristic.money%>);
var min_money = parseInt($("#temp_hidden").text());

var health = parseInt($("#health").text());
var cheerfulness = parseInt($("#cheerfulness").text());
var money = parseInt($("#money").text());

var img_1 = '<%= image_tag("1.jpg", id: "valera", class:"col img") %>';
var img_2 = '<%= image_tag("2.jpg", id: "valera", class:"col img") %>';
var img_3 = '<%= image_tag("3.jpg", id: "valera", class:"col img") %>';

if (health >= max_health * 0.7) {
	$("#valera").replaceWith(img_1);
} else if (health >= max_health * 0.4) {
	$("#valera").replaceWith(img_2);
} else {
	$("#valera").replaceWith(img_3);
}

app/views/valera_action/new.erb
<div class="row justify-content-center">
  <div id="action-form" class="sign-up col-3">
    <%= form_for @valera_action_form, url: action_url do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :health %>
      <%= f.number_field :health, class: 'form-control' %>

      <%= f.label :mana %>
      <%= f.number_field :mana, class: 'form-control' %>

      <%= f.label :cheerfulness %>
      <%= f.number_field :cheerfulness, class: 'form-control' %>

      <%= f.label :fatigue %>
      <%= f.number_field :fatigue, class: 'form-control' %>

      <%= f.label :money %>
      <%= f.number_field :money, class: 'form-control' %>

      <%= f.submit %>
    <% end %>

  </div>
</div>